separate op-program-eigenda-proxy-e2e-tests out

diff --git a/.github/workflows/test-golang.yml b/.github/workflows/test-golang.yml
--- a/.github/workflows/test-golang.yml
+++ b/.github/workflows/test-golang.yml
@@ -53,6 +53,56 @@ jobs:
           - op-alt-da
           - op-e2e/system/altda
           - op-e2e/actions/altda
+    steps:
+      - uses: actions/checkout@v4
+
+      - uses: jdx/mise-action@v2
+        with:
+          version: 2024.12.14 # [default: latest] mise version to install
+          install: true # [default: true] run `mise install`
+          cache: true # [default: true] cache mise using GitHub's cache
+          experimental: true # [default: false] enable experimental features
+
+      - name: Restore cached forge artifacts cached
+        uses: actions/cache@v3
+        id: cache-restore
+        with:
+          path: packages/contracts-bedrock/forge-artifacts
+          key: ${{ runner.os }}-forge-${{ hashFiles('packages/contracts-bedrock/src/**/*.sol') }}
+
+      # Cache has been stored in the build-and-cache-contracts job, so if this fails there's a problem
+      - name: Check cache restore
+        if: steps.cache-restore.outputs.cache-hit != 'true'
+        run: |
+          echo "Cache restore failed"
+          exit 1
+
+      # We use mise to install golang instead of the setup-go action,
+      # so we need to do the cache setup ourselves
+      - name: Go Module Cache
+        uses: actions/cache@v3
+        id: go-cache
+        with:
+          path: ~/go/pkg/mod
+          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
+          restore-keys: |
+            ${{ runner.os }}-go-
+
+      # Add explicit download on cache miss
+      # go test runs `go mod download` implicitly, but this separation is nice to see how long downloading vs running tests takes
+      - name: Download Go modules
+        if: steps.go-cache.outputs.cache-hit != 'true'
+        run: go mod download
+
+      - name: Run tests
+        run: |
+          go test -timeout=10m ./${{ matrix.packages }}/...
+
+  op-eigenda-e2e-tests:
+    needs: [go-tests]
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
     services:
       eigenda-proxy:
         image: ghcr.io/layr-labs/eigenda-proxy:v1.8.1
@@ -105,10 +155,6 @@ jobs:
       - name: Download Go modules
         if: steps.go-cache.outputs.cache-hit != 'true'
         run: go mod download
-
-      - name: Run tests
-        run: |
-          go test -timeout=10m ./${{ matrix.packages }}/...
 
       - name: Run Op program with eigenda proxy test
         run: |
